# Generated by Django 6.1.1 on 2026-09-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=20),
        ),
    ]
