# Generated by Django 6.1.1 on 2026-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_django", "0002_user_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
